FROM oracle/graalvm-ce:1.0.0-rc10
EXPOSE 8080
COPY target/christmas-tree-controller-*.jar christmas-tree-controller.jar
ADD . target
RUN java -cp christmas-tree-controller.jar io.micronaut.graal.reflect.GraalClassLoadingAnalyzer \
    && native-image --no-server \
             --allow-incomplete-classpath \
             --enable-http \
             --enable-https \
             --enable-url-protocols=http,https \
             --enable-all-security-services \
             --class-path christmas-tree-controller.jar \
             -H:ReflectionConfigurationFiles=target/reflect.json \
             -H:IncludeResources="logback.xml|application.yml|META-INF/services/*.*" \
             -H:Name=christmas-tree-controller \
             -H:Class=nl.pvanassen.christmas.tree.controller.Application \
             -H:+ReportUnsupportedElementsAtRuntime \
             -H:+AllowVMInspection \
             -H:-UseServiceLoaderFeature \
             --rerun-class-initialization-at-runtime='sun.security.jca.JCAUtil$CachedSecureRandomHolder,javax.net.ssl.SSLContext,org.apache.http.conn.ssl.SSLConnectionSocketFactory' \
             --delay-class-initialization-to-runtime=io.netty.handler.codec.http.HttpObjectEncoder,io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder,io.netty.handler.ssl.util.ThreadLocalInsecureRandom,com.sun.jndi.dns.DnsClient

ENTRYPOINT ["./christmas-tree-controller", "-Dmicronaut.config.files=/config/application-docker.yml"]
