app:
  debug: ${DEBUG:false}
  tasmota:
    host: ${ESPURNA_HOST:localhost}
    apiKey: ${EsPURNA_APIKEY:12345678}
  leds:
    strips: ${LED_STRIPS:16} # Yeah dunno about that
    leds-per-strip: ${LEDS_PER_STRIP:20}  # Yeah dunno about that
    fps: ${FPS:30}
    seconds: ${SECONDS:25}
    opc:
      hostname: ${OPC_HOSTNAME:localhost}
      port: ${OPC_PORT:7890}
