app:
  tasmota:
    host: "$TASMOTA_HOST:localhost"
  brightness:
    host: "$BRIGHTNESS_HOST:localhost"
    port: "$BRIGHTNESS_PORT:80"
    min: "$BRIGHTNESS_MIN:0.3"
  leds:
    fps: "$FPS:60"
    seconds: "$SECONDS:25"
    opc:
      host: "$OPC_HOST:localhost"
      port: "$OPC_PORT:7890"
  mqtt:
    host: "$MQTT_HOST:localhost"
    port: "$MQTT_PORT:1883"
  debug: "$DEBUG:false"
  ip: "$IP:"
  hostname: "$HOSTNAME:"
  cron:
    power-on: "$CRON_POWER_ON:0 55 6 ? * * *"
    full-on: "$CRON_FULL_ON:0 5 7 ? * * *"
    shutting-down: "$CRON_SHUTTING_DOWN:0 0 21 ? * * *"
    shutdown: "$CRON_SHUTDOWN:0 5 21 ? * * *"
    firework: "$CRON_FIREWORK:0 59 23 31 12 * *"